spring:
  application:
    name: eureka-turbine
server:
  port: 10026
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
turbine:
  app-config: eureka-consumer,eureka-consumer-feign-hystrix
  cluster-name-expression: "default"

