spring:
  application:
    name: eureka-consumer-feign-hystrix
  boot:
    admin:
      url: http://localhost:10030
  zipkin:
    base-url: http://localhost:10050
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 10025
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    prefer-ip-address: true


