spring:
  application:
    name: eureka-consumer-feign-hystrix
  boot:
    admin:
      url: http://localhost:10030
server:
  port: 10025
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    prefer-ip-address: true


