spring:
  application:
    name: eureka-consumer-feign-zipkin
  zipkin:
    base-url: http://zipkin-server/
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 10027
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/

