server:
  port: 10050
spring:
  application:
    name: zipkin-server
#  boot:
#    admin:
#      url: http://localhost:10010
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10010/eureka/

#spring:
#  zipkin:
#    base-url: http:localhost:10031
#  sleuth:
#    sampler:
#      percentage: 1.0
