spring:
  profiles: default
  application:
    name: eureka-consumer
server:
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:${server.port}/eureka/
---
spring:
  profiles: test
  application:
    name: eureka-consumer-test
server:
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://root:root@192.168.17.238:${server.port}/eureka/

