spring:
  application:
    name: eureka-consumer-feign-hystrix
server:
  port: 10025
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:10010/eureka/
feign:
  hystrix:
    enabled: true

