spring:
  application:
    name: cloud-consumer
  boot:
    admin:
      url: http://localhost:10030
server:
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/cloud/
  instance:
    prefer-ip-address: true