spring:
  application:
    name: eureka-consumer
  boot:
    admin:
      url: http://localhost:10011
server:
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    prefer-ip-address: true