spring:
  application:
    name: eureka-provider-feign-hystrix-zipkin
  boot:
    admin:
      url: http://localhost:10011
  zipkin:
    base-url: http://localhost:10012
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
