spring:
  application:
    name: eureka-provider-feign
  boot:
    admin:
      url: http://localhost:10011
server:
  port: 10020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
